services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.2-r3-ls420             # https://github.com/linuxserver/docker-qbittorrent/releases
    container_name: qbittorrent
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      TORRENTING_PORT: ${QBITORRENT_TORRENTING_HOST_PORT}
    networks:
      - cluster_network
    volumes:
      - ${HOME}/NAS/qbittorrent/appdata:/config                       # Contains all relevant configuration files.
      - ${HOME}/NAS/qbittorrent/downloads:/downloads                  # Location of downloads on disk. This will be mapped to a different folder 
    restart: ${RESTART_POLICY}