# TODO /homepage/config/services.yaml add remote compose https://gethomepage.dev/configs/compose
# TODO server.yaml migrate to named volumes
# docker images --format "{{ .Size }} \t {{ .Repository }}" | sort -h

networks:
  cluster_network:          # Docker Swarm overlay network
    external: true

volumes:
  prowlarr-data:
    name: prowlarr-data
    driver: local
  arr-data:
    name: arr-data # TODO change volume type. Avoid /home.
    driver: local
      #    data
      #    ├── torrents
      #    │   ├── books
      #    │   ├── movies
      #    │   ├── music
      #    │   └── tv
      #    ├── usenet
      #    │   ├── incomplete
      #    │   └── complete
      #    │       ├── books
      #    │       ├── movies
      #    │       ├── music
      #    │       └── tv
      #    └── media
      #        ├── books
      #        ├── movies
      #        ├── music
      #        └── tv
  mkdocs-data:
    name: mkdocs-data # TODO

include:
  # Apps
  - path:
      - compose/server/apps/it-tools.yaml
      - compose/server/apps/change-detection.yaml          
      - compose/server/apps/code-server.yaml
      - compose/server/apps/omni-tools.yaml   
      - compose/server/apps/networking-toolbox.yaml  
      - compose/server/apps/convertx.yaml    
      - compose/server/apps/raid-calculator.yaml    
      - compose/server/apps/excalidraw.yaml
  # - path:
  #     - compose/server/apps/rocketchat.yaml                       # Mongodb container Crashes. requires AVX CPU instruction set
  #   env_file:
  #     - env/.rocketchat.env
      # - compose/server/apps/documentation.yaml                    # Crashes.
  - path: 
      - compose/server/apps/jsoncrack.yaml                          
      - compose/server/apps/stirling.yaml                           # 1.88GB. Consider using latest-ultra-lite tag
      - compose/server/apps/web-check.yaml                          # 2.71GB
  - path: 
      - compose/server/apps/mirotalk.yaml                           # Requires pulling the Github repo first and install from bash script
                                                                    # https://github.com/miroslavpejic85/mirotalk
    env_file:
      - mirotalk/.mirotalk.env

  # Arr
  - path:
      - compose/server/arr/jellyseerr.yaml                          # 1.42 GB. 
      - compose/server/arr/prowlarr.yaml
      - compose/server/arr/radarr.yaml
      # - compose/server/arr/readarr.yaml                           # This image is deprecated. We will not offer support for this image and it will not be updated.
      - compose/server/arr/sonarr.yaml

  # Tunnel
  - path:
      - compose/server/management/cloudflare.yaml
  
  # Proxy
  - path:
      - compose/server/management/dockerproxy.yaml
