---
networks:
  cluster-network:          # Docker Swarm overlay network
    external: true

include:
  # Apps
  - path:
    - compose/server/apps/archive.yaml
    - compose/server/apps/it-tools.yaml
    - compose/server/apps/change-detection.yaml
    - compose/server/apps/code-server.yaml
    - compose/server/apps/omni-tools.yaml
    - compose/server/apps/scanopy.yaml
    - compose/server/apps/networking-toolbox.yaml
    - compose/server/apps/convertx.yaml
    - compose/server/apps/raid-calculator.yaml
    - compose/server/apps/excalidraw.yaml
    - compose/server/apps/gitlab.yaml
    - compose/server/apps/jsoncrack.yaml
    - compose/server/apps/stirling.yaml
    - compose/server/apps/bentopdf.yaml
    - compose/server/apps/web-check.yaml
  # Observability
  - path:
    - compose/server/observability/cadvisor.yaml
    - compose/server/observability/grafana.yaml
    - compose/server/observability/prometheus.yaml
    - compose/server/observability/uptime-kuma.yaml
  # Arr
  - path:
    - compose/server/arr/jellyseerr.yaml
    - compose/server/arr/prowlarr.yaml
    - compose/server/arr/radarr.yaml
    - compose/server/arr/sonarr.yaml
  # Tunnel
  - path:
    - compose/server/management/cloudflare.yaml
  # Proxy
  - path:
    - compose/server/management/dockerproxy.yaml
...
