networks:
  internal_network:
    driver: bridge

volumes:
  grafana-storage: {} # TODO change volume type
  kuma-data: {} # TODO I'll keep the configuration but not the logging
  portainer-data: {} # TODO change volume tipe
  gitea-data: {} # TODO change volume type
  media: {} # TODO change volume type
  arr-data: {} # TODO change volume type
  prometheus-data: {} # TODO change volume type

## Monitoring and root apps

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment: # TODO pass ports in the config file to env variables
      TZ: ${TZ}
      HOMEPAGE_VAR_IP: ${IP}
      HOMEPAGE_VAR_CALENDAR: ${CALENDAR_URL}
    networks:
      - internal_network
    ports:
      - ${HOMEPAGE_HOST_PORT}:${HOMEPAGE_CONTAINER_PORT}
    volumes:
      - ${HOMEPAGE_HOST_CONFIG}:${HOMEPAGE_CONTAINER_CONFIG} 
      - ${DOCKER_SOCK}:${DOCKER_SOCK}  # path to docker.sock. Requires running the container as root
      - ${HOMEPAGE_HOST_IMAGES}:${HOMEPAGE_CONTAINER_IMAGES}
    restart: unless-stopped

  glances:
    image: docker.io/nicolargo/glances:latest-full
    container_name: glances
    environment:
      - "GLANCES_OPT=-w"
      - TZ=${TZ}
    networks:
      - internal_network
    ports:
      - ${GLANCES_HOST_PORT}:${GLANCES_CONTAINER_PORT}
    volumes:
      - ${DOCKER_SOCK}:${DOCKER_SOCK} # path to docker.sock
    restart: unless-stopped

  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${UPTIMEKUMA_HOST_PORT}:${UPTIMEKUMA_CONTAINER_PORT}
    volumes:
      - kuma-data:${UPTIMEKUMA_CONTAINER_DATA}
      - ${DOCKER_SOCK}:${DOCKER_SOCK} # path to docker.sock
    restart: unless-stopped

  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    environment:
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${PROMETHEUS_HOST_PORT}:${PROMETHEUS_CONTAINER_PORT}
    volumes: # TODO Add volume and persist the data
      - ${PROMETHEUS_HOST_CONFIG}:${PROMETHEUS_CONTAINER_CONFIG} # path to /etc/prometheus.yml
    depends_on:
      - cadvisor
    restart: unless-stopped
  
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    environment:
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
    - ${CADVISOR_HOST_PORT}:${CADVISOR_CONTAINER_PORT}
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
    restart: unless-stopped

  redis:
    image: docker.io/redis:latest
    container_name: redis
    environment:
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
    - ${REDIS_HOST_PORT}:${REDIS_HOST_PORT}
    restart: unless-stopped

  grafana:
    image: docker.io/grafana/grafana-enterprise:latest
    container_name: grafana
    environment:
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${GRAFANA_HOST_PORT}:${GRAFANA_CONTAINER_PORT}
    volumes:
      - grafana-storage:${GRAFANA_CONTAINER_DATA}
    restart: unless-stopped

  portainer-ce:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer
    environment:
      TZ: ${TZ}
    networks:
      - internal_network
    ports:  #TODO
      - 9443:9443 #HTTPS Login
      # - 8000:8000 #TCP Optional. required if you plan to use the Edge compute features with Edge agents.
      - 9000:9000 #HTTP Login  in use
    volumes:  # TODO
      - portainer-data:/data' # TODO
      - ${DOCKER_SOCK}:${DOCKER_SOCK} # path to docker.sock
    restart: unless-stopped

## Non-root Apps

  it-tools: 
    image: docker.io/corentinth/it-tools:latest
    container_name: "it_tools"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${ITTOOLS_HOST_PORT}:${ITTOOLS_CONTAINER_PORT}
    restart: unless-stopped

  web-check: 
    image: docker.io/lissy93/web-check:latest
    container_name: Web-Check
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${WEBCHECK_HOST_PORT}:${WEBCHECK_CONTAINER_PORT}
    restart: unless-stopped

  codeServer:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${CODE_HOST_PORT}:${CODE_CONTAINER_PORT}
    volumes: # TODO map volume
      - ${CODE_HOST_CONFIG}:${CODE_CONTAINER_CONFIG}
    restart: unless-stopped
  

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    env_file:
      - env/.jellyfin.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${JELLYFIN_HOST_PORT}:${JELLYFIN_CONTAINER_PORT}
      - ${JELLYFIN_HOST_PORT_HTTPS}:${JELLYFIN_CONTAINER_PORT_HTTPS}
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    volumes:
      - media:${JELLYFIN_CONTAINER_CONFIG} # TODO switch to volume
    devices:
      - /dev/dri:/dev/dri # Allows the application to access the render and iGPU devices
    restart: unless-stopped

  stirling: # TODO fix connection
    image: docker.io/stirlingtools/stirling-pdf:latest
    container_name: stirling
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_ENABLE_SECURITY=false
      - LANGS="en_US"
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      #SECURITY_LOGINMETHOD: "none"
      #SECURITY_OAUTH2_ENABLED: false
    networks:
      - internal_network
    ports:
      - ${STIRLING_HOST_PORT}:${STIRLING_CONTAINER_PORT}
    volumes:
      - ./stirlingPDF/trainingData:/usr/share/tessdata #Required for extra OCR languages
      - ./stirlingPDF/extraConfigs:/configs
    restart: unless-stopped

  gitea:
    image: docker.io/gitea/gitea:latest
    container_name: gitea
    environment:
      # USER: git
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${GITEA_HOST_PORT}:${GITEA_CONTAINER_PORT}
      - ${GITEA_HOST_SSH_PORT}:${GITEA_CONTAINER_SSH_PORT}
    volumes: # TODO move to named volume
      # - gitea-data:/data # app.ini in /var/lib/docker/volumes/server_gitea-data
      # /data/gitea/gitea.db container path to the sqlite3 database
      - ${GITEA_HOST_DATA}:${GITEA_CONTAINER_DATA}
      - ${GITEA_HOST_CONFIG}:${GITEA_CONTAINER_CONFIG}
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

## ARR Stack

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - env/.arr.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${RADARR_HOST_PORT}:${RADARR_CONTAINER_PORT}
    volumes:
      - arr-data:/config
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - env/.arr.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${SONARR_HOST_PORT}:${SONARR_CONTAINER_PORT}
    volumes:
      - ${RADARR_HOST_CONFIG}:${RADARR_CONTAINER_CONFIG}
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    env_file:
      - env/.arr.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${JACKETT_HOST_PORT}:${JACKETT_CONTAINER_PORT}
    volumes:
      - ${JACKETT_HOST_CONFIG}:${JACKETT_CONTAINER_CONFIG}
      - ${JACKETT_HOST_BLACKHOLE}:${JACKETT_CONTAINER_BLACKHOLE}
    restart: unless-stopped

  jellyseerr:
    image: docker.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    env_file:
      - env/.arr.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${JELLYSEERR_HOST_PORT}:${JELLYSEERR_CONTAINER_PORT}
    volumes:
      - ${JELLYSEERR_HOST_CONFIG}:${JELLYSEERR_CONTAINER_CONFIG}
    restart: unless-stopped


