networks:
  internal_network:
    driver: bridge

services:
# Traefik reverse proxy
  traefik:
    image: traefik:latest 
    container_name: traefik
    environment:
      TZ: ${TZ}
    networks:
      - internal_network
    command:
      # Enable a tls challenge named "myresolver"
      #- "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      #- "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      # Tell to store the certificate on a path under our volume
      #- "--certificatesresolvers.myresolver.acme.storage=/config/certs/acme.json"
    ports: 
      - 80:80
      - 443:443
      - 8080:8080 # (Optional) Enable Dashboard, don't do in production as the API does not require authentication
    volumes:
      - ${DOCKER_SOCK}:${DOCKER_SOCK}
      - ./traefik/config:/etc/traefik/ # Static configuration path
      - ./traefik/certs:/etc/traefik/certs # Create a certs folder where letsencrypt will store the certificates
    restart: unless-stopped

  ##IT Tools for testing
  it-tools: 
    image: docker.io/corentinth/it-tools:latest
    container_name: "IT_Tools"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${ITTOOLS_HOST_PORT}:${ITTOOLS_CONTAINER_PORT}
    labels:
      - "traefik.enable=true" # Explicitly tell Traefik to expose this container
      - "traefik.http.routers.ittools.rule=Host(`tardis.ittools.localhost`)" # The domain the service will respond to tardis.ittools
      - "traefik.http.routers.ittools.entrypoints=http, https" # Allow request only from the predefined entry point named "http"
    restart: unless-stopped