services:
  gitea:                                                          # Web ports 3000. SSH port 2222
    image: docker.io/gitea/gitea:1.24.6-rootless
    user: ${PUID}
    container_name: gitea
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: gitea-postgress:5432
      GITEA__database__NAME: gitea
      GITEA__database__USER: gitea
      GITEA__database__PASSWD: gitea
    networks:
      - cluster_network
      - gitea_network
    volumes: 
      - gitea-data:/var/lib/gitea
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - gitea-postgress 
    restart: ${RESTART_POLICY}

  gitea-postgress:
    image: docker.io/library/postgres:14
    restart: ${RESTART_POLICY}
    networks:
      - gitea_network
    container_name: gitea-postgress
    environment:
      POSTGRES_USER: gitea
      POSTGRES_PASSWORD: gitea
      POSTGRES_DB: gitea
    volumes:
      - gitea-postgres:/var/lib/postgresql/data

volumes:
  gitea-db:
    name: gitea-db
    driver: local
  gitea-config:
    name: gitea-config
    driver: local
  gitea-data:
    name: gitea-data
    driver: local
  gitea-postgres:
    name: gitea-postgres
    driver: local

networks:
  gitea_network:
    name: gitea_network
    driver: bridge

    