services:
  cloudflared: # Cloudfare tunnel
    image: cloudflare/cloudflared:latest
    container_name: server-tunnel
    command: tunnel --no-autoupdate run
    environment:
      TUNNEL_TOKEN: ${SERVER_CLOUDFARE_TUNNEL_TOKEN}
    networks:
      - internal_network
    extra_hosts: # Explictly defines the hostnames. Equivalent to write on /etc/hosts within the container
      - ${SECURITY_SUBDOMAIN_NAME}:${SECURITY_IP}
      - ${SERVER_SUBDOMAIN_NAME}:${SERVER_IP}
      - ${NAS_SUBDOMAIN_NAME}:${NAS_IP}
    depends_on:
      - homepage
    restart: ${RESTART_POLICY}