services:
  traefik:
    image: traefik:v3.4 
    container_name: traefik
    environment:
      TZ: ${TZ}
      SECURITY_IP: ${SECURITY_IP}
      SERVER_IP: ${SERVER_IP}
      NAS_IP: ${NAS_IP}
      DOCKER_SOCK: "/var/run/docker.sock"

      # Traefik specific
      SERVER_SUBDOMAIN_NAME: ${SERVER_SUBDOMAIN_NAME}
      SECURITY_SUBDOMAIN_NAME: ${SECURITY_SUBDOMAIN_NAME}
      NAS_SUBDOMAIN_NAME: ${NAS_SUBDOMAIN_NAME}
      DOMAIN_NAME: ${DOMAIN_NAME}

      # Cloudflare Specific
      CF_DNS_API_TOKEN: ${CLOUDFLARE_DNS_API_TOKEN}
      CLOUDFLARE_EMAIL: ${EMAIL}
    command:
      - --configFile=/etc/traefik/config/global/static.yaml
    networks: 
      - cluster_network
    ports:
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro                        # So that Traefik can listen to the Docker events
      - "${HOME}/Security/traefik:/etc/traefik"                             # Mounts the traefik folder
                                                                            # permissions 644 for /etc/traefik/acme.json are too open, please use 600
    restart: ${RESTART_POLICY}
    