services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:1.23.16
    container_name: uptime-kuma
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
      - cluster_network
    volumes:
      - kuma-data:/app/data # ./uptime_kuma/data:/app/data
      - ${DOCKER_SOCK}:${DOCKER_SOCK}:ro # path to docker.sock
    restart: ${RESTART_POLICY}

volumes:
  kuma-data:
    name: kuma-data  # TODO I'll keep the configuration but not the logging