[crio.image]
signature_policy = "/etc/crio/policy.json"
pause_image="registry.k8s.io/pause:3.10"

[crio.runtime]
default_runtime = "crun"
conmon_cgroup = "pod"
cgroup_manager = "cgroupfs"

[crio.runtime.runtimes.crun]
runtime_path = "/usr/libexec/crio/crun"
runtime_root = "/run/crun"
monitor_path = "/usr/libexec/crio/conmon"
allowed_annotations = [
    "io.containers.trace-syscall",
]

[crio.runtime.runtimes.runc]
runtime_path = "/usr/libexec/crio/runc"
runtime_root = "/run/runc"
monitor_path = "/usr/libexec/crio/conmon"