# ( --- Static Configuration --- )

global:
  checkNewVersion: true
  sendAnonymousUsage: false

providers:
  file:
    directory: /etc/traefik  # this is the path within the traefik container where the static config is stored. This must be mounted in the volumes section of the docker compose file.
    debugLogGeneratedTemplate: true
    watch: true # Set the watch option to true to allow Traefik to automatically watch for file changes

api:
  dashboard: true # Enables Traefik dashboard
  insecure: true # Enable the API in insecure mode.
  disabledashboardad: true
  debug: true # Enable additional endpoints for debugging and profiling, served under /debug/

log:
  level: ERROR # Switch to ERROR in production env
  filePath: /etc/traefik/logs/traefik.log # Mount this path in the volumes section of the docker compose
  format: common  # format [common, json, logfmt]
  maxBackups: 3 # maximum number of old log files to retain.
  maxAge: 7 # maximum number of days to retain old log files based on the timestamp encoded in their filename
  
accesslog:
  format: common  # format [common, json, logfmt]
  addInternals: true # Enables access logs for internal resources 
  filePath: /etc/traefik/logs/access.log

tracing:
  addInternals: true
  serviceName: traefik

metrics:
  addInternals: true
  prometheus:
    addEntryPointsLabels: true # Enable metrics on entry points.
    addRoutersLabels: true # Enable metrics on routers.
    addServicesLabels: true # Enable metrics on services.
    entryPoint: metrics
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0

entryPoints:
  web:
    address: ":80"
    observability:
      tracing: true # Enables tracing for http
    http: # Redirect to https
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    observability:
      tracing: true # Enables tracing for https
    address: ":443"
  metrics:
    address: :8082

# ( --- Dynamic Configuration --- )

certificatesResolvers:
  cloudflareResolver:
    acme:
      email: '{{env "TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_EMAIL"}}'
      storage: /etc/traefik/acme.json
      # https://acme-v02.api.letsencrypt.org/directory
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10
        disablePropagationCheck: true
        resolvers: # Explicitly add Cloudflare resolvers
          - "1.1.1.2:53"
          - "1.0.0.2:53"

http:
  routers:
  # ( --- Security Routers--- )
    portainer:
      entryPoints: # Allows request only from the predefined entry points named "web" and "websecure" (http and https respectively).
        - websecure
      rule: Host(`{{env "SECURITY_SUBDOMAIN_NAME"}}.portainer.{{env "DOMAIN_NAME"}}`)
      service: portainer # References the service
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    traefik:
      entryPoints:
        - websecure
      rule: Host(`{{env "SECURITY_SUBDOMAIN_NAME"}}.traefik.{{env "DOMAIN_NAME"}}`)
      service: traefik
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true 
 
    pihole:  # TODO Fix redirection rule to /admin
      entryPoints:
        - websecure
      rule: Host(`{{env "SECURITY_SUBDOMAIN_NAME"}}.pihole.{{env "DOMAIN_NAME"}}`)
      service: pihole
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    whatsupdocker: 
      entryPoints:
        - websecure
      rule: Host(`{{env "SECURITY_SUBDOMAIN_NAME"}}.whatsupdocker.{{env "DOMAIN_NAME"}}`)
      service: whatsupdocker
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    authelia:
      entryPoints:
        - websecure
      rule: Host(`{{env "SECURITY_SUBDOMAIN_NAME"}}.authelia.{{env "DOMAIN_NAME"}}`)
      service: authelia
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

  # ( --- Server Routers--- )

    homepage: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.{{env "DOMAIN_NAME"}}`)
      service: homepage
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    dozzle: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.dozzle.{{env "DOMAIN_NAME"}}`)
      service: dozzle
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    glances: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.glances.{{env "DOMAIN_NAME"}}`)
      service: glances
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    uptimekuma: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.uptimekuma.{{env "DOMAIN_NAME"}}`)
      service: uptimekuma
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    prometheus: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.prometheus.{{env "DOMAIN_NAME"}}`)
      service: prometheus
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    cadvisor: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.cadvisor.{{env "DOMAIN_NAME"}}`)
      service: cadvisor
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    grafana: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.grafana.{{env "DOMAIN_NAME"}}`)
      service: grafana
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    ittools: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.ittools.{{env "DOMAIN_NAME"}}`)
      service: ittools
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    webcheck: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.webcheck.{{env "DOMAIN_NAME"}}`)
      service: webcheck
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    codeserver: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.codeserver.{{env "DOMAIN_NAME"}}`)
      service: codeserver
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    stirling: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.stirling.{{env "DOMAIN_NAME"}}`)
      service: stirling
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    changedetection: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.changedetection.{{env "DOMAIN_NAME"}}`)
      service: changedetection
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    radarr: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.radarr.{{env "DOMAIN_NAME"}}`)
      service: radarr
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    sonarr: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.sonarr.{{env "DOMAIN_NAME"}}`)
      service: sonarr
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    prowlarr: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.prowlarr.{{env "DOMAIN_NAME"}}`)
      service: prowlarr
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    readarr: 
      entryPoints:
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.readarr.{{env "DOMAIN_NAME"}}`)
      service: readarr 
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    jellyseerr: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.jellyseerr.{{env "DOMAIN_NAME"}}`)
      service: jellyseerr
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    jsoncrack: 
      entryPoints: 
        - websecure
      rule: Host(`{{env "SERVER_SUBDOMAIN_NAME"}}.jsoncrack.{{env "DOMAIN_NAME"}}`)
      service: jsoncrack
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

  # ( --- NAS Routers--- )
    jellyfin: 
      entryPoints: 
        - web
        - websecure
      rule: Host(`{{env "NAS_SUBDOMAIN_NAME"}}.jellyfin.{{env "DOMAIN_NAME"}}`)
      service: jellyfin
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    gitea: 
      entryPoints: 
        - web
        - websecure
      rule: Host(`{{env "NAS_SUBDOMAIN_NAME"}}.gitea.{{env "DOMAIN_NAME"}}`)
      service: gitea
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    qbittorrent: 
      entryPoints: 
        - web
        - websecure
      rule: Host(`{{env "NAS_SUBDOMAIN_NAME"}}.qbittorrent.{{env "DOMAIN_NAME"}}`)
      service: qbittorrent
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

    netbootxyz: 
      entryPoints: 
        - web
        - websecure
      rule: Host(`{{env "NAS_SUBDOMAIN_NAME"}}.netbootxyz.{{env "DOMAIN_NAME"}}`)
      service: netbootxyz
      tls:
        certResolver: cloudflareResolver
      observability:
        accessLogs: true
        tracing: true
        metrics: true

  services:
  # ( --- Security Services--- )
    portainer: # Names the services
      loadBalancer:
        servers:
          - url: http://{{env "SECURITY_IP"}}:{{env "PORTAINER_HTTP_HOST_PORT"}} # Specify the port to be used by the service. Does not map to the correct port unless explicitly specified.
            preservePath: true  # The preservePath option allows to preserve the URL path. When a health check is configured for the server, the path is not preserved.
        passHostHeader: true

    traefik:
      loadBalancer:
        servers:
          - url: http://{{env "SECURITY_IP"}}:{{env "TRAEFIK_DASHBOARD_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    pihole:
      loadBalancer:
        servers:
          - url: http://{{env "SECURITY_IP"}}:{{env "PIHOLE_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    whatsupdocker:
      loadBalancer:
        servers:
          - url: http://{{env "SECURITY_IP"}}:{{env "WHATSUPDOCKER_HOST_PORT"}}
            preservePath: true 
        passHostHeader: true

    authelia: 
      loadBalancer:
        servers:
          - url: http://{{env "SECURITY_IP"}}:{{env "AUTHELIA_HOST_PORT"}} 
            preservePath: true
        passHostHeader: true

  # ( --- Server Services--- )
  
    homepage:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "HOMEPAGE_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    dozzle:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "DOZZLE_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    glances:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "GLANCES_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    uptimekuma:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "UPTIMEKUMA_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    prometheus:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "PROMETHEUS_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    cadvisor:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "CADVISOR_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    grafana:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "GRAFANA_HOST_PORT"}}
            preservePath: true
        passHostHeader: true  

    ittools:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "ITTOOLS_HOST_PORT"}}
            preservePath: true
        passHostHeader: true 

    webcheck:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "WEBCHECK_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    codeserver:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "CODE_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    stirling:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "STIRLING_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    changedetection:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "CHANGEDETECTION_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    radarr:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "RADARR_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    sonarr:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "SONARR_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    prowlarr:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "PROWLARR_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    readarr:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "READARR_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    jellyseerr:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "JELLYSEERR_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    jsoncrack:
      loadBalancer:
        servers:
          - url: http://{{env "SERVER_IP"}}:{{env "JSONCRACK_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

  # ( --- NAS Services--- )
    jellyfin:
      loadBalancer:
        servers:
          - url: http://{{env "NAS_IP"}}:{{env "JELLYFIN_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    gitea:
      loadBalancer:
        servers:
          - url: http://{{env "NAS_IP"}}:{{env "GITEA_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    qbittorrent:
      loadBalancer:
        servers:
          - url: http://{{env "NAS_IP"}}:{{env "QBITORRENT_UI_HOST_PORT"}}
            preservePath: true
        passHostHeader: true

    netbootxyz:
      loadBalancer:
        servers:
          - url: http://{{env "NAS_IP"}}:{{env "NETBOOT_HOST_TCP_PORT"}}
            preservePath: true
        passHostHeader: true