services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    environment:
      TZ: ${TZ}
      PGID: ${PGID}
      PUID: ${PUID}
    networks:
      - cluster_network
      - cadvisor_network
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
    - redis
    restart: ${RESTART_POLICY}

  redis:
    image: docker.io/redis:latest
    container_name: "cadvisor-redis"
    environment:
      TZ: ${TZ}
    networks:
      - cadvisor_network
    ports:
    - ${REDIS_HOST_PORT}:${REDIS_HOST_PORT}
    restart: ${RESTART_POLICY}

networks:
  cadvisor_network:
    driver: bridge
    name: cadvisor_network
