services:
  dozzle:
    image: docker.io/amir20/dozzle:v8.12.17
    container_name: "dozzle"
    environment:
      TZ: ${TZ}
      DOZZLE_HOSTNAME: ${SERVER_SUBDOMAIN_NAME}
      DOZZLE_REMOTE_HOST: tcp://${SECURITY_IP}:2375|${SECURITY_SUBDOMAIN_NAME} #,tcp://${NAS_IP}:2375|${NAS_SUBDOMAIN_NAME}  # https://dozzle.dev/guide/agent#how-to-connect-to-an-agent
                                                                              # Enable access to the CONTAINER API in the docker proxy
      DOZZLE_NO_ANALYTICS: true
    networks:
      - internal_network
    ports:
      - ${DOZZLE_HOST_PORT}:${DOZZLE_CONTAINER_PORT}
    volumes:
      - ${DOCKER_SOCK}:${DOCKER_SOCK}
    restart: ${RESTART_POLICY}