services:
  glances:
    image: docker.io/nicolargo/glances:latest-full
    container_name: glances
    environment:
      - "GLANCES_OPT=-w"
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    networks:
      - server_network
    volumes:
      - ${DOCKER_SOCK}:${DOCKER_SOCK} # path to docker.sock
    restart: ${RESTART_POLICY}