services:
  prometheus:
    image: docker.io/prom/prometheus:latest
    container_name: prometheus
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
      - cluster_network
    volumes: # TODO Add volume and persist the data
      - ${HOME}/Server/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml # path to /etc/prometheus.yml
    depends_on:
      - cadvisor
    restart: ${RESTART_POLICY}

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: "prometheus-node_exporter"
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    volumes:
      - '/:/host:ro,rslave'
    restart: ${RESTART_POLICY}

# TODO migrate node_exporter to standalone deployment