services:
  uptime-kuma:
    image: docker.io/louislam/uptime-kuma:latest
    container_name: uptime-kuma
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
      - internal_network
    volumes:
      - kuma-data:/app/data # ./uptime_kuma/data:/app/data
      - ${DOCKER_SOCK}:${DOCKER_SOCK}:ro # path to docker.sock
    restart: ${RESTART_POLICY}