services:
  cloudflared:
    image: cloudflare/cloudflared:2026.3.0
    container_name: server-tunnel
    command: tunnel --loglevel error --no-autoupdate run
    environment:
      TZ: ${TZ}
      TUNNEL_TOKEN: ${SERVER_CLOUDFARE_TUNNEL_TOKEN}
    networks:
      - cluster-network
    restart: ${RESTART_POLICY}