# Usage:
#     mkdir -p ~/archivebox/data && cd ~/archivebox
#     curl -fsSL 'https://docker-compose.archivebox.io' > docker-compose.yml
#     docker compose run archivebox version
#     docker compose run archivebox config --set SAVE_ARCHIVEDOTORG=False
#     docker compose run archivebox add --depth=1 'https://news.ycombinator.com'
#     docker compose run -T archivebox add < bookmarks.txt
#     docker compose up -d && open 'https://localhost:8000'
#     docker compose run archivebox help
# Documentation:
#     https://github.com/ArchiveBox/ArchiveBox/wiki/Docker#docker-compose

services:
  archivebox:
    image: archivebox/archivebox:0.7.3
    container_name: archive
    environment:
      ADMIN_USERNAME:                                                     # creates an admin user on first run with the given user/pass combo
      ADMIN_PASSWORD: 
      ALLOWED_HOSTS: "archive.${SERVER_SUBDOMAIN_NAME}.${DOMAIN_NAME}"    # set this to the hostname(s) you're going to serve the site from!
      CSRF_TRUSTED_ORIGINS: http://archive:8000                           # you MUST set this to the server's URL for admin login and the REST API to work
      PUBLIC_INDEX: False                 # set to False to prevent anonymous users from viewing snapshot list
      PUBLIC_SNAPSHOTS: False             # set to False to prevent anonymous users from viewing snapshot content
      PUBLIC_ADD_VIEW: False              # set to True to allow anonymous users to submit new URLs to archive
      PUID: 1000                          # set to your host user's UID & GID if you encounter permissions issues
      PGID: 1000                          # UID/GIDs lower than 500 may clash with system uids and are not recommended
    volumes:
    - ${HOME}/Server/archive/data:/data   # Move to S3
    networks:
    - cluster-network
    restart: ${RESTART_POLICY}
    # For more info, see: https://github.com/ArchiveBox/ArchiveBox/wiki/Docker#configuration

    

