services:
  changedetection:
    image: lscr.io/linuxserver/changedetection.io:0.50.18
    container_name: changedetection
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - cluster-network
    volumes:
      - ${HOME}/Server/changedetection/config:/config
    restart: ${RESTART_POLICY}