services:
  codeServer:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      SUDO_PASSWORD: "test"
    networks:
      - cluster_network
    volumes: # TODO 
      - ${HOME}/Server/code-server/config:/config
    restart: ${RESTART_POLICY}