services:
  convertx:
    image: ghcr.io/c4illin/convertx:v0.14.1                   # https://github.com/C4illin/ConvertX
    container_name: convertx
    restart: ${RESTART_POLICY}
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      ALLOW_UNAUTHENTICATED: "true"                           # Allow unauthenticated users to use the service, only set this to true locally
      AUTO_DELETE_EVERY_N_HOURS: 24                           # Auto delete files older than n hours, set to 0 to disable
      HTTP_ALLOWED: true                                      # Allow HTTP connections, set to false to only allow HTTPS
    networks:
      - cluster-network
    volumes:
      - ${HOME}/Server/convertx/data:/app/data                # sudo chown -R $USER:$USER path