services:
  documentation:
    image: docker.io/squidfunk/mkdocs-material:latest
    container_name: documentation
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - cluster-network
    volumes:
      - "${HOME}/Server/mkdocs:/docs" # TODO map to named volume documentation-data
    restart: ${RESTART_POLICY}