services:
  it-tools: 
    image: docker.io/corentinth/it-tools:latest
    container_name: "it-tools"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - cluster_network
    restart: ${RESTART_POLICY}