services:
  it-tools: 
    image: docker.io/corentinth/it-tools:2024.10.22-7ca5933
    container_name: "it-tools"
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - cluster-network
    restart: ${RESTART_POLICY}