services:
  jsoncrack:
    image: jsoncrack
    container_name: jsoncrack
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      NODE_ENV: "production[cristian@mechanicus jsoncrack.com]$"
    networks:
      - server_network
    restart: ${RESTART_POLICY}