services:
  mirotalk:
    image: mirotalk/p2p:latest
    container_name: mirotalk
    hostname: mirotalk
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    restart: ${RESTART_POLICY}
    networks:
      - cluster_network
    volumes:
      - ${HOME}/Server/mirotalk/.mirotalk.env:/src/.env:ro
        # Rebranding:
      - ${HOME}/Server/mirotalk/app/src/config.js:/src/app/src/config.js:ro
        # Optional volumes for real-time updates:
        # - ./app/:/src/app/:ro
        # - ./public/:/src/public/:ro
