services:
  omni-tools:
    image: iib0011/omni-tools:0.6.0
    container_name: omni-tools
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - cluster-network
    restart: ${RESTART_POLICY}