services:
  raid-calculator:
    image: ghcr.io/lissy93/raid-calculator:1.0.0
    build: 
      context: https://github.com/Lissy93/raid-calculator.git
    container_name: raid-calculator
    restart: ${RESTART_POLICY}
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
      - cluster-network