services:

  rocketchat:
    image: ${IMAGE:-registry.rocket.chat/rocketchat/rocket.chat}:${RELEASE:-latest}
    restart: ${RESTART_POLICY}
    labels:
      prometheus.io/scrape: "true"
      prometheus.io/port: ${METRICS_PORT:-9458}
    environment:
      # ROOT_URL: ${ROOT_URL:-http://localhost}
      PORT: ${PORT:-3000}
      DEPLOY_METHOD: docker
      DEPLOY_PLATFORM: compose
      REG_TOKEN: ${REG_TOKEN:-}
      LICENSE_DEBUG: true
      OVERWRITE_SETTING_Prometheus_Enabled: true
      OVERWRITE_SETTING_Prometheus_Port: "${METRICS_PORT:-9458}"
      MONGO_URL: ${MONGO_URL:-mongodb://mongodb:27017/rocketchat?replicaSet=rs0}
      TRANSPORTER: "${NATS_URL-monolith+nats://nats:4222}"
      INSTANCE_IP: "${INSTANCE_IP:-}"
    expose:
      - ${PORT:-3000}
      - ${METRICS_PORT:-9458}
    ports:
      - "${BIND_IP:-0.0.0.0}:${HOST_PORT:-3000}:${PORT:-3000}"
      - "${BIND_IP:-0.0.0.0}:${METRICS_PORT:-9458}:${METRICS_PORT:-9458}"
    networks:
      - cluster_network
      - rocketchat_internal_network
    # healthcheck:
    #   test: ["CMD", "nc", "-zv", "-w", "10", "rocketchat", "${PORT:-3000}"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 30s

  nats:
    image: docker.io/nats:${NATS_VERSION:-2.11-alpine}
    restart: always
    expose:
      - 4222
      - 8222
      - 6222
    # healthcheck:
    #   test: ["CMD", "nc", "-zv", "-w", "10", "nats", "4222"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 30s
    command: --http_port 8222
    networks:
      - rocketchat_internal_network
      
  mongodb:
    image: docker.io/mongo:${MONGODB_VERSION:-6.0}
    restart: ${RESTART_POLICY}
    volumes:
      - ${MONGODB_HOST_PATH:-mongodb_data}:/data/db:rw    
    command: ["--replSet", "${MONGODB_REPLICA_SET_NAME:-rs0}", "--bind_ip_all", "--port", "${MONGODB_PORT_NUMBER:-27017}"]
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-admin}
      ACK_MONGODB_BITNAMI_MIGRATION: ${ACK_MONGODB_BITNAMI_MIGRATION:?Please refer to https://github.com/RocketChat/rocketchat-compose?tab=readme-ov-file#advanced-migrating-to-oficial-mongodb}
    # healthcheck:
    #   test: ["CMD", "mongosh", "--host", "mongodb", "--port", "${MONGODB_PORT_NUMBER:-27017}", "--eval", "db.adminCommand('ping')"]
    #   interval: 30s
    #   timeout: 30s
    #   retries: 10
    #   start_period: 30s
    expose:
      - ${MONGODB_PORT_NUMBER:-27017}
    ports:
      - "${MONGODB_BIND_IP:-127.0.0.1}:${MONGODB_PORT_NUMBER:-27017}:${MONGODB_PORT_NUMBER:-27017}"
    networks:
      - rocketchat_internal_network

  mongodb-init:
    image: docker.io/mongo:${MONGODB_VERSION:-6.0}
    restart: on-failure
    command:
      - bash
      - -c
      - |
        # $$ is to use the bash $ or this will be interpreted by docker/podman and use variables from env
        # for the MONGODB_PORT_NUMBER we actually want to use the one from the .env
        echo "Waiting for MongoDB to be ready"
        until mongosh --host mongodb --port ${MONGODB_PORT_NUMBER:-27017} --eval "db.adminCommand('ping')" >/dev/null 2>&1; do
          echo "Waiting for MongoDB to be ready..."
          sleep 5
        done
        echo "MongoDB ready"
        REPLICA_STATUS="$(mongosh --host mongodb --port ${MONGODB_PORT_NUMBER:-27017} --eval "rs.status().ok" 2>/dev/null || echo "")"
        if [ -z "$$REPLICA_STATUS" ]; then
          echo "Initializing the replica set..."
          mongosh --host mongodb --port ${MONGODB_PORT_NUMBER:-27017} --eval "rs.initiate({_id: '${MONGODB_REPLICA_SET_NAME:-rs0}', members: [{ _id: 0, host: 'mongodb:${MONGODB_PORT_NUMBER:-27017}' }]})"
        else
          echo "Replica set already initialized."
          exit 0
        fi
        sleep 1
        # Check if the replicaset is initialized
        REPLICA_STATUS=$(mongosh --host mongodb --port ${MONGODB_PORT_NUMBER:-27017} --eval "rs.status().ok" 2>/dev/null || echo "")
        if [ -z "$$REPLICA_STATUS" ]; then
          echo "Replica set not initialized."
        else
          echo "Replica set already initialized."
        fi
    depends_on:
      - mongodb
    networks:
      - rocketchat_internal_network

  # nats-exporter:
  #   image: docker.io/natsio/prometheus-nats-exporter:${NATS_EXPORTER_VERSION:-0.17.3}
  #   depends_on:
  #     - nats
  #   expose:
  #     - 7777
  #   command:
  #     - -healthz
  #     - -varz
  #     - "http://nats:8222"
  #   networks:
  #     - rocketchat_internal_network

  # mongodb-exporter:
  #   image: docker.io/percona/mongodb_exporter:${MONGODB_EXPORTER_VERSION:-0.44.0}
  #   depends_on:
  #     - mongodb
  #   expose:
  #     - 9216
  #   command:
  #     - --mongodb.uri=${MONGODB_URI:-mongodb://mongodb:27017}
  #     - --collect-all
  #     - --compatible-mode
  #   networks:
  #     - rocketchat_internal_network
      
volumes:
  mongodb_data:
    driver: local

networks:
  rocketchat_internal_network:
    name: rocketchat_internal_network
    driver: bridge