services:
  web-check: 
    image: docker.io/lissy93/web-check:latest
    container_name: web-check
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - server_network
    restart: ${RESTART_POLICY}