services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - internal_network
    ports:
      - ${PROWLARR_HOST_PORT}:${PROWLARR_CONTAINER_PORT}
    volumes: # TODO
      - prowlarr-data:/config # Database and Prowlarr configs
    restart: ${RESTART_POLICY}