# For configuration options and examples, please see:
# http://gethomepage.dev/latest/configs/services

- Traefik:
    - Traefik:
        href: https://{{HOMEPAGE_VAR_SECURITY_SUBDOMAIN_NAME}}.traefik.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Traefik
        icon: traefik.png
        ping: http://{{HOMEPAGE_VAR_SECURITY_IP}}:{{HOMEPAGE_VAR_TRAEFIK}} # TODO endpoint shows healthy but not running
        server: docker-security 
        container: traefik
        widget:
            type: traefik
            url: https://{{HOMEPAGE_VAR_SECURITY_SUBDOMAIN_NAME}}.traefik.{{HOMEPAGE_VAR_DOMAIN_NAME}}
            # username: username # optional
            # password: password # optional

- Metrics:
    - CPU Usage:
        widget:
            type: glances
            version: 4
            url: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.glances.{{HOMEPAGE_VAR_DOMAIN_NAME}}
            metric: cpu
    - Memory Usage:
        widget:
            type: glances
            version: 4
            url: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.glances.{{HOMEPAGE_VAR_DOMAIN_NAME}}
            metric: memory
    - Disk I/O:
        widget:
            type: glances
            version: 4
            url: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.glances.{{HOMEPAGE_VAR_DOMAIN_NAME}}
            metric: disk:sda
            chart: true
    - System Info:
        widget:
            type: glances
            version: 4
            url: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.glances.{{HOMEPAGE_VAR_DOMAIN_NAME}}
            metric: info

- Prometheus:
    - Target Overview:
        widget:
            type: prometheus
            url: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.prometheus.{{HOMEPAGE_VAR_DOMAIN_NAME}}
    - CPU Usage Average:
        widget:
            type: prometheusmetric
            url: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.prometheus.{{HOMEPAGE_VAR_DOMAIN_NAME}}
            refreshinterval: 15000
            metrics:
                - label: Average CPU/min
                  query: 'avg without (mode,cpu) (1 - rate(node_cpu_seconds_total{mode="idle", job="server"}[1m]))'
                  format:
                    type: number
                    scale: 100
                    suffix: "%"
    - Docker Disk and Memory:
        widget:
            type: prometheusmetric
            url: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.prometheus.{{HOMEPAGE_VAR_DOMAIN_NAME}}
            refreshinterval: 15000
            metrics:
                - label: Disk I/O
                  query: sum(container_blkio_device_usage_total{name!~""}) # container_fs_io_current{name!~""}
                  format:
                    type: bytes
                - label: Memory Used
                  query: sum(container_memory_usage_bytes{name!~""}) 
                  format:
                    type: bytes
    - Docker Network Sent:
        widget:
            type: prometheusmetric
            url: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.prometheus.{{HOMEPAGE_VAR_DOMAIN_NAME}}
            refreshinterval: 15000
            metrics:
                - label: Total Sent
                  query: sum(container_network_transmit_bytes_total{name!~""})
                  format:
                    type: bytes
                - label:  Total Errors
                  query: sum(container_network_transmit_errors_total{name!~""})
                  format:
                    type: bytes
                - label:  Total Dropped
                  query: sum(container_network_transmit_packets_dropped_total{name!~""})
                  format:
                    type: bytes
    - Docker Network Received:
        widget:
            type: prometheusmetric
            url: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.prometheus.{{HOMEPAGE_VAR_DOMAIN_NAME}}
            refreshinterval: 15000
            metrics:
                - label: Total Received
                  query: sum(container_network_receive_bytes_total{name!~""})
                  format:
                    type: bytes
                - label:  Total Errors
                  query: sum(container_network_receive_errors_total{name!~""})
                  format:
                    type: bytes
                - label:  Total Dropped
                  query: sum(container_network_receive_packets_dropped_total{name!~""})
                  format:
                    type: bytes

- Observability:
    - Uptime Kuma:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.uptimekuma.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: "L7 and L4 health checks"
        icon: http://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/uptime-kuma.png
        ping: http://uptime-kuma:3306
        server: docker-server
        container: uptime-kuma
    - Prometheus:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.prometheus.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Prometheus
        icon: http://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prometheus.png
        ping: http://prometheus:9090
        server: docker-server
        container: prometheus
    - Grafana:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.grafana.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Grafana
        icon: http://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/grafana.png
        ping: http://grafana:3000
        server: docker-server
        container: grafana
    - Glances:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.glances.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Glances
        icon: glances.png
        ping: http://glances:61208
        server: docker-server
        container: glances
    - cAdvisor:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.cadvisor.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Detailed Container metrics
        icon: cadvisor.png
        ping: http://cadvisor:8080
        server: docker-server
        container: cadvisor
    - Dozzle:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.dozzle.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Container logging
        icon: dozzle.png
        ping: http://dozzle:8080
        server: docker-server
        container: dozzle

- Server:
    - IT Tools:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.ittools.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Interesting IT Aplications (quality of life improvement)
        icon: kubernetes.png
        ping: http://it-tools:3000
        server: docker-server
        container: it-tools
    - Web Check:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.webcheck.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Website analysis
        icon: chrome.png
        ping: http://web-check:3000
        server: docker-server
        container: web-check
    - Code Server:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.codeserver.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: VS Code
        icon: vscode.png
        ping: http://code-server:8443
        server: docker-server
        container: code-server
    - Stirling:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.stirling.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Stirling PDF
        icon: stirling-pdf.png
        ping: http://stirling:8080
        server: docker-server
        container: stirling
    - Change Detection:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.changedetection.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Change Detection
        icon: changedetection.png
        ping: http://changedetection:5000
        server: docker-server
        container: changedetection
    - MKDocs:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.mkdocs.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: MKDocs TODO
        icon: mkdocs.png
        ping: http://documentation:8000
        server: docker-server
        container: documentation
    - Jsoncrack:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.jsoncrack.{{HOMEPAGE_VAR_DOMAIN_NAME}}/editor
        description: jsoncrack
        icon: mdi-code-braces
        ping: http://jsoncrack:8080
        server: docker-server
        container: jsoncrack
    - Mirotalk:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.meet.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Videoconference
        icon: google-meet
        ping: http://mirotalk:3000
        server: docker-server
        container: mirotalk
    - Prowlarr:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.prowlarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: prowlarr indexer
        icon: prowlarr.png
        ping: http://prowlarr:9696
        server: docker-server
        container: prowlarr
    - Sonarr:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.sonarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Sonarr for Movies
        icon: sonarr.png
        ping: http://sonarr:8989
        server: docker-server
        container: sonarr
    - Radarr:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.radarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Radarr for TV Shows
        icon: radarr.png
        ping: http://radarr:7878
        server: docker-server
        container: radarr
    - Readarr:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.readarr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Readarr for Books
        icon: readarr.png
        ping: http://readarr:8787
        server: docker-server
        container: readarr
    - Jellyseerr:
        href: https://{{HOMEPAGE_VAR_SERVER_SUBDOMAIN_NAME}}.jellyseerr.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Jellyseer
        icon: jellyseerr.png
        ping: http://jellyseerr:5055
        server: docker-server
        container: jellyseerr

- Security:
    - Portainer:
        href: https://{{HOMEPAGE_VAR_SECURITY_SUBDOMAIN_NAME}}.portainer.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Portainer
        icon: portainer.png
        server: docker-security
        container: portainer
    - Pihole:
        href: https://{{HOMEPAGE_VAR_SECURITY_SUBDOMAIN_NAME}}.pihole.{{HOMEPAGE_VAR_DOMAIN_NAME}}/admin/login  
        description: Pihole DNS
        icon: pi-hole.png
        server: docker-security
        container: pihole
    - Whats Up Docker:
        href: https://{{HOMEPAGE_VAR_SECURITY_SUBDOMAIN_NAME}}.whatsupdocker.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Update docker images
        icon: whats-up-docker.png
        server: docker-security 
        container: whatsupdocker
    - Authentik:
        href: https://{{HOMEPAGE_VAR_SECURITY_SUBDOMAIN_NAME}}.authentik.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Auhtnentication and Authorization service
        icon: authentik.png
        server: docker-security
        container: authentik

- NAS:
    - Jellyfin:
        href: https://{{HOMEPAGE_VAR_NAS_SUBDOMAIN_NAME}}.jellyfin.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Jellyfin media player
        icon: http://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/jellyfin.svg
        server: docker-nas
        container: jellyfin
    - Gitea:
        href: https://{{HOMEPAGE_VAR_NAS_SUBDOMAIN_NAME}}.gitea.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: Gitea. Private GIT repo in the cloud 
        icon: gitea.png
        server: docker-nas
        container: gitea
    - NetbootXYZ:
        href: https://{{HOMEPAGE_VAR_NAS_SUBDOMAIN_NAME}}.netbootxyz.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: NetbootXYZ 
        icon: netboot.png
        server: docker-nas
        container: netbootxyz
    - QBitorrent:
        href: https://{{HOMEPAGE_VAR_NAS_SUBDOMAIN_NAME}}.qbitorrent.{{HOMEPAGE_VAR_DOMAIN_NAME}}
        description: qbittorrent
        icon: qbittorrent.png
        server: docker-nas
        container: qbittorrent

- Steam:
    - Profile:
        widget:
            type: iframe
            id: profile
            name: Jamoncín
            src: {{HOMEPAGE_VAR_STEAM}}
            classes: h-max sm:h-60 md:h-60 lg:h-60 xl:h-60 2xl:h-72  # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
            referrerPolicy: same-origin # optional, no default
            allowPolicy: autoplay; fullscreen; gamepad # optional, no default
            allowFullscreen: false # optional, default: true
            loadingStrategy: eager # optional, default: eager
            allowScrolling: no # optional, default: yes
            refreshInterval: 0 #ptional, no default
    - Achievements:
        widget:
            type: iframe
            name: Jamoncín's Achievements
            src: /images/achievement_showcase.jpg
            classes: h-max sm:h-60 md:h-60 lg:h-60 xl:h-60 2xl:h-72 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
            referrerPolicy: same-origin # optional, no default
            allowPolicy: autoplay; fullscreen; gamepad # optional, no default
            allowFullscreen: false # optional, default: true
            loadingStrategy: eager # optional, default: eager
            allowScrolling: no # optional, default: yes
            refreshInterval: 0 #ptional, no default
    - Dalek Empire Discord:
        widget:
            type: iframe
            name: Dalek Empire
            src: https://discord.com/widget?id={{HOMEPAGE_VAR_DISCORD_ID}}&theme=dark
            classes: h-auto sm:h-60 md:h-60 lg:h-60 xl:h-60 2xl:h-72 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
            referrerPolicy: same-origin # optional, no default
            allowPolicy: autoplay; fullscreen; gamepad # optional, no default
            allowFullscreen: false # optional, default: true
            loadingStrategy: eager # optional, default: eager
            allowScrolling: no # optional, default: yes
            refreshInterval: 0 # optional, no default          

- Calendar:
    - Calendar:
        widget:
            type: calendar
            firstDayInWeek: monday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            integrations:
              - type: ical
                url: {{HOMEPAGE_VAR_CALENDAR}}
                name: Cristian
                color: zinc
                params: # optional - additional params for the service
                showName: true
    - Agenda:
        widget:
            type: calendar
            view: agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            previousDays: 3 # optional - shows events since three days ago - defaults to 0
            integrations:
              - type: ical
                url: {{HOMEPAGE_VAR_CALENDAR}}
                name: Cristian
                color: zinc
                params: # optional - additional params for the service
                showName: true