# For configuration options and examples, please see:
# http://gethomepage.dev/latest/configs/services

- Metrics:
  - CPU Usage:
      widget:
        type: glances
        version: 4
        url: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GLANCES}}
        metric: cpu
  - Memory Usage:
      widget:
        type: glances
        version: 4
        url: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GLANCES}}
        metric: memory
  - Disk I/O:
      widget:
        type: glances
        version: 4
        url: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GLANCES}}
        metric: disk:sda
        chart: true
  - System Info:
      widget:
        type: glances
        version: 4
        url: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GLANCES}}
        metric: info

- Prometheus:
    - Target Overview:
        widget:
            type: prometheus
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_PROMETHEUS}}
    - CPU Usage Average:
        widget:
            type: prometheusmetric
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_PROMETHEUS}}
            refreshinterval: 15000
            metrics:
                - label: Average CPU/min
                  query: 'avg without (mode,cpu) (1 - rate(node_cpu_seconds_total{mode="idle", job="server"}[1m]))'
                  format:
                    type: number
                    scale: 100
                    suffix: "%"
    - Docker Disk and Memory:
        widget:
            type: prometheusmetric
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_PROMETHEUS}}
            refreshinterval: 15000
            metrics:
                - label: Disk I/O
                  query: sum(container_blkio_device_usage_total{name!~""}) # container_fs_io_current{name!~""}
                  format:
                    type: bytes
                - label: Memory Used
                  query: sum(container_memory_usage_bytes{name!~""}) 
                  format:
                    type: bytes
    - Docker Network Sent:
        widget:
            type: prometheusmetric
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_PROMETHEUS}}
            refreshinterval: 15000
            metrics:
                - label: Total Sent
                  query: sum(container_network_transmit_bytes_total{name!~""})
                  format:
                    type: bytes
                - label:  Total Errors
                  query: sum(container_network_transmit_errors_total{name!~""})
                  format:
                    type: bytes
                - label:  Total Dropped
                  query: sum(container_network_transmit_packets_dropped_total{name!~""})
                  format:
                    type: bytes
    - Docker Network Received:
        widget:
            type: prometheusmetric
            url: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_PROMETHEUS}}
            refreshinterval: 15000
            metrics:
                - label: Total Received
                  query: sum(container_network_receive_bytes_total{name!~""})
                  format:
                    type: bytes
                - label:  Total Errors
                  query: sum(container_network_receive_errors_total{name!~""})
                  format:
                    type: bytes
                - label:  Total Dropped
                  query: sum(container_network_receive_packets_dropped_total{name!~""})
                  format:
                    type: bytes

- Monitoring & Logging:
    - Uptime Kuma:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_UPTIMEKUMA}}
        description: "L7 and L4 health checks"
        icon: http://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/uptime-kuma.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_UPTIMEKUMA}}
        showStats: true
        server: docker-internal
        container: uptime-kuma
    - Prometheus:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_PROMETHEUS}}
        description: Prometheus
        icon: http://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prometheus.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_PROMETHEUS}}
        showStats: true
        server: docker-internal
        container: prometheus
    - Grafana:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GRAFANA}}
        description: Grafana
        icon: http://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/grafana.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GRAFANA}}
        showStats: true
        server: docker-internal
        container: grafana
    - Glances:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GLANCES}}
        description: Glances
        icon: glances.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GLANCES}}
        showstats: true
        server: docker-internal
        container: glances
    - cAdvisor:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_CADVISOR}}
        description: Detailed Container metrics
        icon: cadvisor.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_CADVISOR}}
        showstats: true
        server: docker-internal
        container: cadvisor

- Apps:
    - Jellyfin:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_JELLYFIN}}
        description: Jellyfin media player
        icon: http://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons@master/svg/jellyfin.svg
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_JELLYFIN}}
        showStats: true
        server: docker-internal
        container: jellyfin
    - IT Tools:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_ITTOOLS}}
        description: Interesting IT Aplications (quality of life improvement)
        icon: kubernetes.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_ITTOOLS}}
        showstats: true
        server: docker-internal
        container: it_tools
    - Web Check:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_WEBCHECK}}
        description: Website analysis
        icon: chrome.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_WEBCHECK}}
        showstats: true
        server: docker-internal
        container: Web-Check
    - Code Server:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_CODE}}
        description: VS Code
        icon: vscode.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_CODE}}
        showstats: true
        server: docker-internal
        container: code-server
    - Gitea:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GITEA}}
        description: Gitea. Private GIT repo in the cloud 
        icon: gitea.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_GITEA}}
        showstats: true
        server: docker-internal
        container: gitea
    - Stirling:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_STIRLING}}
        description: Stirling PDF
        icon: stirling-pdf.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_STIRLING}}
        showstats: true
        server: docker-internal
        container: stirling
    - Change Detection:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_CHANGEDETECTION}}
        description: Change Detection
        icon: changedetection.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_CHANGEDETECTION}}
        showstats: true
        server: docker-internal
        container: changedetection
    - Portainer: # TODO add remote docker https://gethomepage.dev/configs/docker/
        href: http://{{HOMEPAGE_VAR_SECURITY_IP}}:{{HOMEPAGE_VAR_PORTAINER}}
        description: Portainer
        icon: portainer.png
        ping: http://{{HOMEPAGE_VAR_SECURITY_IP}}:{{HOMEPAGE_VAR_PORTAINER}}
    - Pihole:
        href: http://{{HOMEPAGE_VAR_SECURITY_IP}}:{{HOMEPAGE_VAR_PIHOLE}}}/admin
        description: Pihole DNS
        icon: pi-hole.png
        ping: http://{{HOMEPAGE_VAR_SECURITY_IP}}:{{HOMEPAGE_VAR_PIHOLE}}
- Arr:
    - Prowlarr:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_PROWLARR}}
        description: prowlarr indexer
        icon: prowlarr.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_PROWLARR}}
        showStats: true
        server: docker-internal
        container: prowlarr
    - Sonarr:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_SONARR}}
        description: Sonarr for Movies
        icon: sonarr.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_SONARR}}
        showStats: true
        server: docker-internal
        container: sonarr
    - Radarr:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_RADARR}}
        description: Radarr for TV Shows
        icon: radarr.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_RADARR}}
        showStats: true
        server: docker-internal
        container: radarr
    - Readarr:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_READARR}}
        description: Readarr for Books
        icon: readarr.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_READARR}}
        showStats: true
        server: docker-internal
        container: readarr
    - Jellyseerr:
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_JELLYSEERR}}
        description: Jellyseer
        icon: jellyseerr.png
        ping: http://{{HOMEPAGE_VAR_SERVER_IP}}:{{HOMEPAGE_VAR_JELLYSEERR}}
        showStats: true
        server: docker-internal
        container: jellyseerr

- Steam:
    - Profile:
        widget:
            type: iframe
            id: profile
            name: Jamoncín
            src: {{HOMEPAGE_VAR_STEAM}}
            classes: h-max sm:h-60 md:h-60 lg:h-60 xl:h-60 2xl:h-72 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
            referrerPolicy: same-origin # optional, no default
            allowPolicy: autoplay; fullscreen; gamepad # optional, no default
            allowFullscreen: false # optional, default: true
            loadingStrategy: eager # optional, default: eager
            allowScrolling: no # optional, default: yes
            refreshInterval: 0 #ptional, no default
    - Achievements:
        widget:
            type: iframe
            name: Jamoncín's Achievements
            src: /images/achievement_showcase.jpg
            classes: h-max sm:h-60 md:h-60 lg:h-60 xl:h-60 2xl:h-72 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
            referrerPolicy: same-origin # optional, no default
            allowPolicy: autoplay; fullscreen; gamepad # optional, no default
            allowFullscreen: false # optional, default: true
            loadingStrategy: eager # optional, default: eager
            allowScrolling: no # optional, default: yes
            refreshInterval: 0 #ptional, no default
    - Dalek Empire Discord:
        widget:
            type: iframe
            name: Dalek Empire
            src: https://discord.com/widget?id={{HOMEPAGE_VAR_DISCORD_ID}}&theme=dark
            classes: h-auto sm:h-60 md:h-60 lg:h-60 xl:h-60 2xl:h-72 # optional, use tailwind height classes, see https://tailwindcss.com/docs/height
            referrerPolicy: same-origin # optional, no default
            allowPolicy: autoplay; fullscreen; gamepad # optional, no default
            allowFullscreen: false # optional, default: true
            loadingStrategy: eager # optional, default: eager
            allowScrolling: no # optional, default: yes
            refreshInterval: 0 # optional, no default
                   

- Calendar:
    - Calendar:
        widget:
            type: calendar
            firstDayInWeek: monday # optional - defaults to monday
            view: monthly # optional - possible values monthly, agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            integrations:
              - type: ical
                url: {{HOMEPAGE_VAR_CALENDAR}}
                name: Cristian
                color: zinc
                params: # optional - additional params for the service
                showName: true
    - Agenda:
        widget:
            type: calendar
            view: agenda
            maxEvents: 10 # optional - defaults to 10
            showTime: true # optional - show time for event happening today - defaults to false
            previousDays: 3 # optional - shows events since three days ago - defaults to 0
            integrations:
              - type: ical
                url: {{HOMEPAGE_VAR_CALENDAR}}
                name: Cristian
                color: zinc
                params: # optional - additional params for the service
                showName: true
