---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings
title: "Cristian's Server"
description: "v0.1"
favicon: /images/Dalek.ico

background:
  image: /images/witcher_wallpaper.jpg
  blur: sm # sm, "", md, xl... see https://tailwindcss.com/docs/backdrop-blur
  saturate: 50 # 0, 50, 100... see https://tailwindcss.com/docs/backdrop-saturate
  brightness: 50 # 0, 50, 75... see https://tailwindcss.com/docs/backdrop-brightness
  opacity: 50 # 0-100

theme: dark
color: slate
language: en
target: _blank # Possible options include _blank, _self, and _top
hideVersion: true
showStats: true
statusStyle: "dot" #basic OR dot
disableCollapse: true
useEqualHeights: true

layout:
  Metrics:
    style: row
    columns: 4
    icon: /images/Tardis.ico
  Prometheus:
    style: row
    columns: 4
    icon: /images/Tardis.ico
  Apps:
    tab: Apps
    style: row
    columns: 5
    icon: /images/Tardis.ico
  Monitoring & Logging:
    tab: Monitoring & Logging
    style: row
    columns: 4
    icon: /images/Tardis.ico
  Arr:
    tab: Arr Stack
    style: row
    columns: 5
    icon: /images/Tardis.ico
  Steam:
    style: row
    columns: 3
    icon: /images/Tardis.ico
  Calendar:
    header: true
    style: row
    columns: 2
    icon: /images/Tardis.ico
