services:
  portainer:
    image: docker.io/portainer/portainer-ce:latest
    container_name: portainer
    command:
      - --http-enabled
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    networks:
      - cluster_network
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: ${RESTART_POLICY}