services:
  whatsupdocker:
    image: docker.io/getwud/wud:8.1.1
    container_name: whatsupdocker
    environment:
      # Security
      WUD_WATCHER_SECURITY_SOCKET: /var/run/docker.sock
      WUD_WATCHER_SECURITY_WATCHBYDEFAULT: true
      WUD_WATCHER_SECURITY_CRON: "0 0 */7 * *"                                        # At 00:00 on day-of-month 7 in every month.

      # # Server
      WUD_WATCHER_SERVER_HOST: http://server-dockerproxy
      WUD_WATCHER_SERVER_PORT: 2375
      WUD_WATCHER_SERVER_WATCHBYDEFAULT: true
      WUD_WATCHER_SERVER_CRON: "0 0 */7 * *"                                          # At 00:00 on day-of-month 7 in every month.

      # # NAS
      WUD_WATCHER_NAS_HOST: http://nas-dockerproxy
      WUD_WATCHER_NAS_PORT: 2375
      WUD_WATCHER_NAS_WATCHBYDEFAULT: true
      WUD_WATCHER_NAS_CRON: "0 0 */7 * *"                                             # At 00:00 on day-of-month 7 in every month.

      # General Options
      WUD_SERVER_ENABLED: true                                                        # API Server endpoint
      TZ: ${TZ}
      WUD_LOG_FORMAT: text
      WUD_LOG_LEVEL: warning

      # Triggers
      WUD_TRIGGER_DISCORD_DALEK_URL: ${DALEK_DISCORD}
      WUD_TRIGGER_DISCORD_DALEK_BOTUSERNAME: "Whatsup Dalek"
      WUD_TRIGGER_DISCORD_DALEK_CARDLABEL: "UPDATE HUMAN!"
      WUD_TRIGGER_DISCORD_DALEK_AUTO: true
      WUD_TRIGGER_DISCORD_DALEK_MODE: batch
      WUD_TRIGGER_DISCORD_DALEK_ONCE: false
    networks:
      - cluster_network
    volumes:
      # - ${HOME}/Server/whatsupdocker/store/wud.json:/store/wud.json                                      # If you want the state to persist after the container removal, you need to mount /store as a volume.
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: ${RESTART_POLICY}