services:
  jellyseerr:
    image: docker.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      LOG_LEVEL: debug
    networks:
      - cluster_network
    volumes:
      - ${HOME}/Server/jellyseerr/config:/app/config
    restart: ${RESTART_POLICY}