services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - cluster_network
    volumes:
      - ${HOME}/Server/radarr/config:/config # ./radarr/config:/config
    restart: ${RESTART_POLICY}