services:
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    networks:
      - cluster_network
    volumes:
      - ${HOME}/Server/readarr/config:/config # Database and Readarr configs
      - ${HOME}/Server/readarr/books:/books # Location of Book library on disk (See note in Application setup) optional
      - ${HOME}/Server/readarr/downloads:/downloads # Location of download managers output directory (See note in Application setup) optional
    restart: ${RESTART_POLICY}